name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          pm2 stop colorbot
          cd colorbot/
          git pull
          npm install
          pm2 start ecosystem.config.js --env production --log-date-format 'DD-MM HH:mm:ss.SSS'